### ISSUE TITLE
Update data on regular basis via Github Actions

### ISSUE THREAD

**Issue by anuveyatsu** [datasets/ppp#3]
## Acceptance criteria

* [ ] Data processing script is running in the CI on a regular basis
  * [ ] To be more explicit: as a result of the CI job, the data in the repo is updated (e.g., it pushes new data back to the repo)

**Comment by datatalking** [comment]
@anuveyatsu So when you say the acceptance criteria is that this data processing script is run on the CI, can you provide a link or tell me more about the setup this repo uses for CI regarding Purchasing Power Parity PPP?

This is a side issue but the repo also references that it is Python2 only? Are there plans to update the code to python3 or is the code been depreciated and we have an alternate already written in python3?

**Comment by anuveyatsu** [comment]
Hi @datatalking It used to run in Travis CI before - https://github.com/datasets/ppp/blob/master/.travis.yml

Now, we need to run it using GitHub Actions - https://github.com/features/actions

**Comment by geoffrey1330** [comment]
@anuveyatsu the cicd pipeline should trigger on on both push and pull request to the master branch right?

**Comment by geoffrey1330** [comment]
@anuveyatsu do i clone and make a pull request to this repository?

**Comment by anuveyatsu** [comment]
@geoffrey1330 yes, please feel free to fork and create pull request. Thank you!

**Comment by geoffrey1330** [comment]
@anuveyatsu here is the pull request. it triggers on push or pull request to the master branch. I tested it and it completed successfully.
https://github.com/datasets/ppp/pull/12

**Comment by anuveyatsu** [comment]
@geoffrey1330 the PR has been merged #12 
However, I've overlooked that the acceptance criteria of this issue is to run the CI job on a regular basis, e.g., on some schedule (monthly).

**Comment by geoffrey1330** [comment]
@anuveyatsu since the PR was merged can i proceed with my application process??

**Comment by geoffrey1330** [comment]
@anuveyatsu are you suggesting a schedule trigger of the pipeline?

**Comment by geoffrey1330** [comment]
@anuveyatsu I added a schedule cron job that runs the CI job first of the month 8:00 am.
here is the pull request 
https://github.com/datasets/ppp/pull/15/

**Comment by anuveyatsu** [comment]
thanks @geoffrey1330 👍

**Comment by geoffrey1330** [comment]
@anuveyatsu should i go ahead with the application process?

**Comment by anuveyatsu** [comment]
Hey @geoffrey1330 it should be in another thread because this is the thread for the issue about GitHub Actions for PPP dataset. Could you just use another thread(e.g., email)?

**Comment by geoffrey1330** [comment]
@anuveyatsu Alright
